DROP DATABASE IF EXISTS testdb;

CREATE DATABASE testdb;

USE testdb;

DROP TABLE IF EXISTS CREDIT;

CREATE TABLE CREDIT (
ID INT NOT NULL AUTO_INCREMENT,
STATUS VARCHAR(200),
AMOUNT DOUBLE,
APPLICATION_SIGNED_HOUR INT,
APPLICATION_SIGNED_WEEKDAY INT,
CITY VARCHAR(200),
COUNTRY VARCHAR(200),
CREDIT_SCORE_ES_EQUIFAX_RISK VARCHAR(200),
DATE_OF_BIRTH VARCHAR(200),
DEBT_TO_INCOME DOUBLE,
EDUCATION INT,
EMPLOYMENT_DURATION_CURRENT_EMPLOYER VARCHAR(200),
EMPLOYMENT_POSITION VARCHAR (200),
EMPLOYMENT_STATUS INT,
EXISTING_LIABILITIES INT,
GENDER INT,
HOME_OWNERSHIP_TYPE INT,
INCOME_FROM_PRINCIPAL_EMPLOYER INT,
INCOME_TOTAL INT,
INTEREST_RATE DOUBLE,
LOAN_DATE VARCHAR(200),
LOAN_DURATION INT,
MARITAL_STATUS INT,
NEW_CREDIT_CUSTOMER BIT,
NO_OF_PREVIOUS_LOANS_BEFORE_LOAN INT,
OCCUPATION_AREA INT,
USE_OF_LOAN INT,
VERIFICATION_TYPE INT,
WORK_EXPERIENCE VARCHAR(200),
PREVIOUS_SCORE DOUBLE,
DEFAULTED BIT,
DEFAULT_DATE VARCHAR(200),
PRIMARY KEY (ID)
)